### ISSUE TITLE
[AUTOCUT] Distribution Build Failed for custom-codecs-2.10.0

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/custom-codecs#38]
***Received Error***: **Error building custom-codecs, retry with: ./build.sh manifests/2.10.0/opensearch-2.10.0.yml --component custom-codecs**.
                      The distribution build for custom-codecs has failed for version: 2.10.0.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/8427/consoleFull

**Comment by gaiksaya** [comment]
Hi @reta @andrross ,

Looks like custom-codecs is failing the build:

```
+ ./gradlew publishToMavenLocal -Dopensearch.version=2.10.0 -Dbuild.snapshot=false -Dbuild.version_qualifier=
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
Invalid Java installation found at '/usr/lib/jvm/temurin-8-jdk-amd64' (Java home). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
Invalid Java installation found at '/usr/lib/jvm/temurin-11-jdk-amd64' (Java home). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
Invalid Java installation found at '/usr/lib/jvm/adoptopenjdk-14-amd64' (Java home). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.3
  OS Info               : Linux 6.1.34-59.116.amzn2023.x86_64 (amd64)
  JDK Version           : 17 (Eclipse Temurin JDK)
  JAVA_HOME             : /opt/java/openjdk-17
  Random Testing Seed   : BFC5AC2FA4125FB0
  In FIPS 140 mode      : false
=======================================

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :generateMetadataFileForNebulaPublication
> Task :generatePomFileForNebulaPublication
> Task :generatePomFileForPluginZipPublication
> Task :javadoc UP-TO-DATE
> Task :javadocJar UP-TO-DATE
> Task :sourcesJar UP-TO-DATE
> Task :publishNebulaPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishNebulaPublicationToMavenLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
   > Invalid publication 'nebula': supplied groupId (org.opensearch) does not match value from POM file (org.opensearch.plugin). Cannot edit groupId directly in the POM file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
10 actionable tasks: 4 executed, 6 up-to-date
2023-09-09 00:34:48 ERROR    Error building custom-codecs, retry with: ./build.sh manifests/2.10.0/opensearch-2.10.0.yml --component custom-codecs
2023-09-09 00:34:48 INFO     Removing /tmp/tmpbrw0p9vy
Traceback (most recent call last):
  File "/var/jenkins/workspace/distribution-build-opensearch@2/./src/run_build.py", line 88, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/distribution-build-opensearch@2/./src/run_build.py", line 69, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch@2/src/build_workflow/builder_from_source.py", line 56, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch@2/src/git/git_repository.py", line 85, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmpbrw0p9vy/custom-codecs/scripts/build.sh -v 2.10.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.
script returned exit code 1
```

**Comment by peterzhuamazon** [comment]
Checking, it was running fine on my setups tho.

**Comment by reta** [comment]
Seems like this line https://github.com/opensearch-project/custom-codecs/blob/main/build.gradle#L45 that was changed is causing the issues

**Comment by peterzhuamazon** [comment]
Resolved here:
* #39

**Comment by reta** [comment]
Thanks a lot @peterzhuamazon , my apologies, I was not out of town for a few days
